sonar.projectKey=rafaelsmorais_lista-tarefas-devops
sonar.organization=rafaelsmorais
sonar.projectName=lista-tarefas-devops
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,backend/src/**/*.test.ts
sonar.sourceEncoding=UTF-8
