sonar.projectKey=rafaelsmorais_lista-tarefas-devops
sonar.organization=rafaelsmorais
sonar.projectName=lista-tarefas-devops
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,backend/src/**/*.test.ts
sonar.coverage.exclusions=backend/src/server.ts,backend/src/database.ts,backend/src/todos.ts,frontend/src/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8
